"""Init

Revision ID: a9f2dd73c4c7
Revises: 
Create Date: 2023-10-29 22:32:35.143869

"""
from typing import Sequence, Union

from alembic import op
import pandas as pd
import sqlalchemy as sa
from sqlalchemy.orm import Session

from src.db.base import sync_engine
from src.apps.pokemon.models import Pokemons

# revision identifiers, used by Alembic.
revision: str = 'a9f2dd73c4c7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lv', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pokemons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('picture', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('str', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('tg', sa.Integer(), nullable=True),
    sa.Column('tf', sa.Integer(), nullable=True),
    sa.Column('lv', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('own_pokemons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('pokemon_id', sa.Integer(), nullable=True),
    sa.Column('hp', sa.Integer(), nullable=True),
    sa.Column('str', sa.Integer(), nullable=True),
    sa.Column('defense', sa.Integer(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True),
    sa.Column('tg', sa.Integer(), nullable=True),
    sa.Column('tf', sa.Integer(), nullable=True),
    sa.Column('lv', sa.Integer(), nullable=True),
    sa.Column('experience', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('use_pokemon_id', sa.Integer(), nullable=True),
    sa.Column('enemy_origin_hp', sa.Integer(), nullable=True),
    sa.Column('enemy_hp', sa.Integer(), nullable=True),
    sa.Column('enemy_str', sa.Integer(), nullable=True),
    sa.Column('enemy_defense', sa.Integer(), nullable=True),
    sa.Column('enemy_speed', sa.Integer(), nullable=True),
    sa.Column('enemy_tg', sa.Integer(), nullable=True),
    sa.Column('enemy_tf', sa.Integer(), nullable=True),
    sa.Column('enemy_lv', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['use_pokemon_id'], ['owned_pokemons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    pokemons = pd.read_csv("./data/pokemons.csv")
    with Session(sync_engine) as session:
        pokemons_dict_array = []
        for row in pokemons.to_dict('records'):
            single_pokemon = Pokemons()
            for key, value in row.items():
                setattr(single_pokemon, key, value)
            pokemons_dict_array.append(single_pokemon)
        session.bulk_save_objects(pokemons_dict_array)
        session.commit()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    op.drop_table('own_pokemons')
    op.drop_table('pokemons')
    op.drop_table('player')
    # ### end Alembic commands ###
